name: License

on:
  merge_group:
    branches: ["main"]
    paths-ignore:
      - 'third_party/**'
  push:
    branches: ["main"]
    paths-ignore:
      - 'third_party/**'
  pull_request:
    branches: ["main"]
    types: [ opened, synchronize, reopened, edited ]
    paths-ignore:
      - 'third_party/**'

jobs:
  check-license:
    runs-on: tenki-standard-large-plus-16c-32g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check licenses
        run: .github/workflows/license.sh
